version: "3.9"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    volumes:
      - rails_docker_dev_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - './.env'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      BOOTSTRAP: ${BOOTSTRAP}
    tty: true
    stdin_open: true
volumes:
  rails_docker_dev_db:
