name: CI
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install packages
        run: |
          yarn install
      - name: Build and run test
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          RAILS_ENV: test
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          sudo apt-get -yqq install libpq-dev libyaml-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec .
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: video-sharing-3.0
          environment_name: video-sharing-3-0-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
